name: env2
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9.19
  - imbalanced-learn>=0.8.0
  - lightgbm==3.3.1
  - matplotlib==3.3.4
  - scikit-learn==0.24.1
  - seaborn==0.11.1
  - pip:
      - numpy==1.21.2
      - pandas==1.2.4
      - tensorflow==2.7.0
      - xgboost==1.5.1
      - protobuf==3.20.3
